/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CMS.view.component;

import CMS.model.Model_Menu;

/**
 *
 * @author trant
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu.setOpaque(false);
        init();
    }
    
    private void init() {
        listMenu.addItem(new Model_Menu("Box", "Sản phẩm", Model_Menu.MenuType.MENU));
        listMenu.addItem(new Model_Menu("Wrench", "Phụ kiện", Model_Menu.MenuType.MENU));
        listMenu.addItem(new Model_Menu("Schedule", "Lịch sửa chữa", Model_Menu.MenuType.MENU));
        listMenu.addItem(new Model_Menu("Bill", "Hóa đơn", Model_Menu.MenuType.MENU));
        listMenu.addItem(new Model_Menu("Employee", "Nhân viên", Model_Menu.MenuType.MENU));
        listMenu.addItem(new Model_Menu("Statistic", "Thống kê", Model_Menu.MenuType.MENU));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        In = new javax.swing.JLabel();
        listMenu = new CMS.view.swing.Menu.ListMenu<>();

        setBackground(new java.awt.Color(255, 255, 255));

        panelTop.setBackground(new java.awt.Color(255, 249, 241));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Title.setForeground(new java.awt.Color(183, 150, 107));
        Title.setText("Car Shop");

        In.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/In.png"))); // NOI18N
        In.setMaximumSize(new java.awt.Dimension(59, 59));
        In.setMinimumSize(new java.awt.Dimension(59, 59));
        In.setPreferredSize(new java.awt.Dimension(28, 28));

        listMenu.setBackground(new java.awt.Color(255, 249, 241));

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(In, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(listMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title)
                    .addComponent(In, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(listMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel In;
    private javax.swing.JLabel Title;
    private CMS.view.swing.Menu.ListMenu<String> listMenu;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
